# Generated by Django 4.1.5 on 2023-02-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_alter_friend_age_alter_friend_name_message"),
    ]

    operations = [
        migrations.RenameField(
        model_name='message',
        old_name='acontent',
        new_name='content'
        )
    ]
